// <auto-generated />
using System;
using BoutiqueManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoutiqueManagement.Migrations
{
    [DbContext(typeof(BoutiqueManagementContext))]
    partial class BoutiqueManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoutiqueManagement.Models.CustomerDetail", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Staff_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Staff_objStaff_ID")
                        .HasColumnType("int");

                    b.HasKey("Customer_ID");

                    b.HasIndex("Staff_objStaff_ID");

                    b.ToTable("CustomerDetail");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.OnlineOrder", b =>
                {
                    b.Property<int>("OnlineOrder_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Delivery_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Estimate_Delivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purchaser_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Service_objService_ID")
                        .HasColumnType("int");

                    b.HasKey("OnlineOrder_ID");

                    b.HasIndex("Service_objService_ID");

                    b.ToTable("OnlineOrder");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.Services", b =>
                {
                    b.Property<int>("Service_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Customer_objCustomer_ID")
                        .HasColumnType("int");

                    b.Property<string>("DressId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Service_ID");

                    b.HasIndex("Customer_objCustomer_ID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JionningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Visa_Finshing_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Staff_ID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.CustomerDetail", b =>
                {
                    b.HasOne("BoutiqueManagement.Models.Staff", "Staff_obj")
                        .WithMany()
                        .HasForeignKey("Staff_objStaff_ID");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.OnlineOrder", b =>
                {
                    b.HasOne("BoutiqueManagement.Models.Services", "Service_obj")
                        .WithMany()
                        .HasForeignKey("Service_objService_ID");
                });

            modelBuilder.Entity("BoutiqueManagement.Models.Services", b =>
                {
                    b.HasOne("BoutiqueManagement.Models.CustomerDetail", "Customer_obj")
                        .WithMany()
                        .HasForeignKey("Customer_objCustomer_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
