SET IDENTITY_INSERT [dbo].[OnlineOrder] ON
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (1, N'Pakistani Dress ', N'Caroline ', N'34 takanini auckland', N'2020-12-18 11:00:00', 1, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (2, N'casual wear', N'Richard', N'83 waterside Dr', N'2020-12-16 13:15:00', 45, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (3, N'Evening Gown', N'Ganeson', N'pyespa  tauranga', N'2020-12-14 15:10:00', 21, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (4, N'Kurties', N'Sam', N'Christchurch 23 lake road', N'2020-12-30 11:11:00', 33, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (5, N'Girls wear', N'lilly', N'21 maitland street frankton', N'2020-12-16 15:12:00', 34, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (6, N'lehenga', N'kashh', N'289 ulster street', N'2020-12-23 13:13:00', 65, NULL)
INSERT INTO [dbo].[OnlineOrder] ([OnlineOrder_ID], [NewOrder], [Purchaser_Name], [Delivery_Address], [Estimate_Delivery], [Service_ID], [Service_objService_ID]) VALUES (7, N'Designer suit', N'Neha', N'4 keddle street', N'2020-12-15 15:14:00', 11, NULL)
SET IDENTITY_INSERT [dbo].[OnlineOrder] OFF
